### ISSUE TITLE
Some substations are rendered with opaque filling

### ISSUE THREAD

**Issue by gustavecha** [openinframap/styles#10]
HI,

I don't manage to know why some substations have this fully opaque filling
https://openinframap.org/#lat=47.92361&lng=5.29016&z=18

https://www.openstreetmap.org/way/120553316

It prevents to see inside features and details, should it be removed or used with 90% alpha ?

**Comment by russss** [comment]
Yeah, this was an unintentional change which crept in with the last style updates. I'll change it to remove the fill at higher zooms.
