### ISSUE TITLE
Handle type=site relations for substations and power plants

### ISSUE THREAD

**Issue by russss** [openinframap/styles#11]
* Pull in relations and relation_members with imposm3
* Outline the extent of the site and label in the centre
* Merge voltages - different site areas could have different voltages
* Likewise with operators...

**Comment by gustavecha** [comment]
IMHO, power substations are always in closed perimeters, even if there can be several distinct perimeters (multipolygon).
Only plants will be mapped with type=site relations.

As a summary :
* Power plants : area, multipolygon relation, site relation
* Power substation : area, multipolygon relation

**Comment by russss** [comment]
I've already done the work to support substations tagged like this - it's basically the same as the way power stations are implemented.

I think it might be useful in the future, especially in cases where there are two adjacent substations with the same name (this is quite common in the UK where the transmission and distribution substations are functionally separate but share a site).

**Comment by gustavecha** [comment]
My point was substations won't be mapped as type=site relations but only as multipolygon.
Since imposm3 converts multipolygon relations as areas, there is no need to deal with relations for substations.

**Comment by russss** [comment]
[Here](http://www.openstreetmap.org/relation/7650296) is a counter-example in London.
![image](https://user-images.githubusercontent.com/45057/34480121-7c1e957c-efa2-11e7-9b18-e8f32f356dd0.png)

The site is known as "Rye House Substation" but it consists of a transmission and a distribution part, which are managed by different operators. This is quite common with substations which are on the site of former power stations.

**Comment by gustavecha** [comment]
This is a good one :)

But relation type=site isn't appropriate.
Since there are only closed areas as members, it should be type=multipolygon.

If there is not a single operator for all areas, there shouldn't be a relation at all.
Despite all have the same name, they may not have the same ref.

We also have the case in France : 
Transmission substation : http://www.openstreetmap.org/way/109817708
Distribution substation : http://www.openstreetmap.org/way/437890971
Only operator=* changes.

**Comment by Gazer75** [comment]
Would a site relation accept other multipoly relations or would I have to add the actual ways?
I'm thinking "site" relation more like a route master for public transport...

Problem with adding the ways is that one cannot define voltages for each part of a separated substation.
There are instances where one part is a simple switching station that then has a short line run to the transformer station. Both share name and operator.

Example: https://www.openstreetmap.org/relation/7871517
Northwest part is a simple switching station with no transformers while the rest is in the southeast part.
Problem here is I can't just tag the bottom one with voltage as it is made up of  several ways shared by the buildings.

**Comment by russss** [comment]
I don't see what the issue is there - you don't need it to be a multipolygon. You can just draw a closed way around all those lines and make it a normal polygon.

**Comment by Gazer75** [comment]
And how would I add a fence between buildings then?

**Comment by russss** [comment]
That's how OSM works. Multipolygons should only be used when mapping single entities which consist of multiple areas, or which have holes in.

**Comment by Gazer75** [comment]
Err, no... If parts of a poly belongs to more than one area then you split and make two multipolys and set the role as outer.

**Comment by gustavecha** [comment]
I see a problem here : "Problem here is I can't just tag the bottom one with voltage as it is made up of several ways shared by the buildings."
Ways shouldn't be shared but buildings and substation perimeter should superpose.
Then you have two closed areas, which can be member of a multipolygon substation, if and only if it's the two substation have the same name/ref and operated by the same company

Do you have pictures of this place please ?

**Comment by Gazer75** [comment]
I never do multiple polys or lines on top of each other that share nodes, cause it is such a mess to deal with later.
Multipolys are there for a reason, to make multiple polys share ways. The thinking that you do it only for multiple complete polys with inner/outer is just simple thinking :)

You can see them both with aerials available in OSM editors, but here is a quick link to Googles image of the area. https://goo.gl/maps/mwv1mUSAbz82

**Comment by gustavecha** [comment]
I wrote "superpose", but it can also surround if fences doesn't connect to buildings.
Anyway, sharing nodes isn't a problem, and a multipolygon relation may also be hard to maintain and be a heavier object additionnaly than a simple polygon.

Are you sure the two fenced substations are the same infrastructure ?

**Comment by Gazer75** [comment]
Yes they are the same. The database have them as one with a single ID and same name and operator.

The original part by the river was in operation in 1928 as our first 132kV station. The switching station nearby was added in 1962 after Tokke power plant was built and they needed more capacity.

**Comment by russss** [comment]
This is now working, finally. (Subject, always, to caching.)
