### ISSUE TITLE
Add support for substation as nodes

### ISSUE THREAD

**Issue by gustavecha** [openinframap/styles#13]
Hi

There are a lot of substations mapped as nodes, because it's sometimes a simple cabinet or their position inside a building can't be given with an area.
Let's add support for node [power=substation] with same render as areas.

This is not properly a bug but an enhancement

All the best

**Comment by russss** [comment]
This depends on the database rebuild but I already have it working on my test database.

**Comment by russss** [comment]
Now present on the main map. Styling might need a few tweaks.
