### ISSUE TITLE
Add petroleum sites

### ISSUE THREAD

**Issue by russss** [openinframap/styles#2]
I think these are usually `landuse=industrial` `industrial=[gas|oil|etc]`.

**Comment by gustavecha** [comment]
Hi

Have a look to pipeline=substation
Those are sites where pipeline are connected to compressors or inspection facilities

**Comment by gustavecha** [comment]
Additionnaly you may be interested to add man_made=pipeline + substance=gas way features

**Comment by russss** [comment]
I should already be showing substance=gas on the petroleum layer, but I'm not entirely sure where I got to with that.

**Comment by gustavecha** [comment]
I don't see this nice one showing up
http://www.openstreetmap.org/way/301866277

**Comment by russss** [comment]
That should be fixed now due to that commit above ^. Caching will mean it might take a day or two to update.

**Comment by gustavecha** [comment]
That's ok, I see the gas pipeline now :)
