### ISSUE TITLE
Render node power substations with point for zooms > 13

### ISSUE THREAD

**Issue by gustavecha** [openinframap/styles#28]
Hi,

Currently, for zooms over 13, points for substations disappear to let the real building polygon on the map.
But when the substation is mapped as a node, nothing is displayed.
Is it possible to make node substations appear with the small dot at every zoom please?

Thanks in advance

**Comment by russss** [comment]
Yeah, this seems to be a bug in, or an issue with my understanding of, Mapbox GL. It's known.

**Comment by russss** [comment]
I fixed this, I think.
