### ISSUE TITLE
Display transformer=distribution as node substations

### ISSUE THREAD

**Issue by flacombe** [openinframap/styles#29]
Rural power networks implies to install minor distribution transformers on top of poles when enough place isn't available on ground or when there is not enough customers to require a powerful substation in a real building.
Is it possible ton consider power=* + transformer=distribution as a substation and display it the same way as nodes with power=substation on them please?

**Comment by russss** [comment]
The wiki [seems to indicate](https://wiki.openstreetmap.org/wiki/Tag:power%3Dpole) that these should be mapped as `power=pole; transformer=yes` - I'm not sure sure if I import the transformer tag yet but I'll look into doing so.

**Comment by gustavecha** [comment]
transformer=distribution is more precise than transformer=yes and it's the same meaning.

**Comment by pyrog** [comment]
Sometimes substations on poles are tagged `power=pole` + `substation=minor_distribution`.

So could you, please,  display the following tags as substations ?

* `power=*` + `transformer=distribution`
* `power=*` + `substation=minor_distribution`

**Comment by Gazer75** [comment]
A power pole combined with substation is a tagging mistake.
The only combination on wiki is transformer=distribution which is kind of stupid.
To make it more in line with the substation values the transformer value should be minor_distribution for these pole mounted ones.

**Comment by flacombe** [comment]
It is currently a tagging mistake but it's not illogical.

A pole with a local distribution transformer is first of all a substation.
Since we map all that stuff together on the same node in OSM, the node should have
power=pole
substation=minor_distribution
transformer=distribution

There will be a proposal on that topic, but it needs time to write
https://wiki.openstreetmap.org/wiki/Proposed_features/Substation_nodes_extension

**Comment by Gazer75** [comment]
Sorry, but no. A pole with a transformer is nothing but that. There is often a mechanical switch to disconnect the transformer, but that is it.
Substations have busbar(s) and switches, usually combined disconnectors and circuit breakers. Even small compensators are that uncommon.

I will down vote any proposal to call a pole with a transformer for a substation.

**Comment by russss** [comment]
I'd rather not have this argument in the issue comments here, but it's worth noting that the IEC vocabulary does include "[pole-mounted substation](http://www.electropedia.org/iev/iev.nsf/display?openform&ievref=605-02-19)". I'm not sure it's worth the effort of changing the tagging and making it more complex, though.

It's likely I will import both of these tags and render them both, as there will be overlap. Neither are imported at the moment so this will have to wait until I reimport.

**Comment by flacombe** [comment]
No problem, we'll have this discussion once the proposal will have been written.

Please note that French DSOs all (160 companies) call a transformer on a pole a "substation".
This is part of the official network documentation and operational terminology.

Thank you Russss to make that global import.

**Comment by pyrog** [comment]
If you use osm2pgl to feed your database, seem possible to use [Lua tag transformations](https://github.com/openstreetmap/osm2pgsql/blob/master/docs/lua.md) to do that.

`power=pole` and `substation=*` → `power=substation`

And new substations on poles could be rendered without reimporting the db 😎

**Comment by pyrog** [comment]
Extract of  mapping.json
```json
         "type_mappings": {
            "points": {
               "power": [
                  "substation",
                  "sub_station"
               ],
               "construction:power": [
                  "substation",
                  "sub_station"
               ]
            },
            "polygons": {
               "power": [
                  "substation",
                  "sub_station"
               ],
               "construction:power": [
                  "substation",
                  "sub_station"
               ]
            }
         },
         "type": "geometry"

```
Could be possible if we map `substation=*`

**Comment by russss** [comment]
This is done now!

**Comment by flacombe** [comment]
This is great, thank you @russss
