### ISSUE TITLE
Voltage ranges and colouring

### ISSUE THREAD

**Issue by Gazer75** [openinframap/styles#35]
The current colouring scheme could use some improvements.

Currently the light brown seem to include 50-99kV? which overlaps two standards.
The purple seem to start at 300kV and change to a thicker line at 400kV? This overlaps on the 275-300 range for purple and thicker line for the 380-420kV.
If the 45-52kV range is included in the green colour segment then there is only one segment left using the thin brown colour.

I propose:
Using the green for 30-52kV and a bit thicker light brown for 66-123kV.
Moving the lower threshold for purple to >300kV.
Change the thicker purple to either ≥380kV or >420kV.
Adding a new colour for lines ≥735kV. Haven't got a good suggestion for a colour on them though.

With the above changes you will at least include two ranges per colour segment.

Voltage ranges (min - max):
6-7.2kV
10-12kV
15-17.5kV
20-24kV
30-36kV
45-52kV
66-72.5kV
110-123kV
132-145kV
150-170kV
220-245kV
275-300kV
330-362kV
380-420kV
500-550kV
735-765kV
765-800kV

**Comment by russss** [comment]
Closing this for the moment, but I would like to revisit when I have the time.
