### ISSUE TITLE
Solar generators are not yet rendered

### ISSUE THREAD

**Issue by pyrog** [openinframap/styles#38]
https://openinframap.org/#15.74/46.531483/5.752563
https://www.openstreetmap.org/way/674127409

Key|Value
-- | --
power|generator
generator:source|solar
generator:method | photovoltaic
generator:type|solar_photovoltaic_panel

<img width="206" alt="capture d ecran 2019-03-03 a 15 23 05" src="https://user-images.githubusercontent.com/2158081/53696552-5cbaa480-3dc8-11e9-9a82-13149b7d4c8c.png"> <img width="207" alt="capture d ecran 2019-03-03 a 15 22 54" src="https://user-images.githubusercontent.com/2158081/53696553-5d533b00-3dc8-11e9-9bbc-526ad1958472.png">

**Comment by russss** [comment]
I've added these now, e.g. [here](https://openinframap.org/#16.4/51.049293/-3.205931). There is a change to the tiles so caching may prevent it showing up immediately everywhere.

However, confusingly, the generators in your example are not present in my database, for some reason. I'm not sure why this is the case - a replication issue perhaps but I'm due a re-import soon.

**Comment by pyrog** [comment]
Thanks 😀
> However, confusingly, the generators in your example are not present in my database, for some reason. 

I cut in pieces the original way [557044854](https://www.openstreetmap.org/way/557044854/history)

**Comment by russss** [comment]
> I cut in pieces the original way [557044854](https://www.openstreetmap.org/way/557044854/history)

That shouldn't matter really - it should be automatically handled for me by [imposm3](https://imposm.org/). Additionally I've never seen any objects missing from my DB before, so it's a bit confusing (and difficult to debug).
