### ISSUE TITLE
Distinguish power towers, poles and portals

### ISSUE THREAD

**Issue by flacombe** [openinframap/styles#4]
Hi,

It would be great to make a difference between poles ans towers on power layer.
Currently, all supports are rendered with a square cased cross whereas it would be better to render poles like dots.
Cross is only nice for towers.

Could it be possible to render power=portal (node or ways) too please ?
Example here http://www.openstreetmap.org/way/367165007 or here http://www.openstreetmap.org/way/532538433

Cheers

**Comment by russss** [comment]
Poles and towers are now rendered differently. Portals will have to wait until we do a reimport (hopefully soon!) They'll also need a symbol...suggestions welcome.

**Comment by gustavecha** [comment]
Poles and tower distinction is fine, i'll think of a symbol for portals

Regarding recent commit, portals can be ways too, where power lines connect with power=insulator nodes
http://www.openstreetmap.org/way/367165007

As to not have to change imports later, can you add them now while we continue to think about the best way to render them ?

**Comment by russss** [comment]
Ah yes, good point. I created #15 to track that change, which will have to be in the next reimport as I don't want to stop the current one now.

**Comment by gustavecha** [comment]
Here is a proposal for power portal as nodes.
[power_portal_node1.zip](https://github.com/openinframap/styles/files/1608726/power_portal_node1.zip)

**Comment by russss** [comment]
This is superseded by #15
