### ISSUE TITLE
Render power=cable differently than power=line or power:minor_line

### ISSUE THREAD

**Issue by pyrog** [openinframap/styles#40]
Could you use e.g. dotted lines to render "underground" power cables ?

<img width="312" alt="capture d ecran 2019-03-04 a 23 42 56" src="https://user-images.githubusercontent.com/2158081/53767834-45b6a800-3ed7-11e9-9ba2-5746ee64398e.png">

https://openinframap.org/#17.9/46.655673/5.777063
https://www.openstreetmap.org/way/666436876

**Comment by russss** [comment]
That already happens for cables which are tagged as `location=underground` or `location=underwater`. I haven't decided if it's worth applying this style to everything tagged `power=cable`

**Comment by pyrog** [comment]
According to the [wiki](https://wiki.openstreetmap.org/wiki/Tag:power%3Dcable#Location), the default value for `location` is `underground`.

**Comment by flacombe** [comment]
You may use dashes for underground cables and dots for others (mainly indoor and overhead).

**Comment by russss** [comment]
> According to the [wiki](https://wiki.openstreetmap.org/wiki/Tag:power%3Dcable#Location), the default value for `location` is `underground`.

So it is. I've updated the style now so underground is the default.

**Comment by pyrog** [comment]
thank you 😀
