### ISSUE TITLE
Display "small" substations as nodes at zoom levels ≤ 16

### ISSUE THREAD

**Issue by pyrog** [openinframap/styles#42]
Substations for minor distribution in "small" buildings or street cabinets aren't very visible at "low" zoom levels.
Especially if they don't have names.

[Zoom 15](https://openinframap.org/#14.9/46.57896/5.74568) Ways are visible with difficulty:
<img width="528" alt="zoom 15" src="https://user-images.githubusercontent.com/2158081/53442579-e4d82d00-3a09-11e9-8e56-6dd74777b021.png">

[Zoom 14](https://openinframap.org/#13.9/46.57896/5.74568) Only nodes are visibles:
<img width="434" alt="zoom 14" src="https://user-images.githubusercontent.com/2158081/53442591-ebff3b00-3a09-11e9-9ab3-01354e17a5f0.png">

[Zoom 13](https://openinframap.org/#12.9/46.57896/5.74568) All substations are visible:
<img width="176" alt="zoom 13" src="https://user-images.githubusercontent.com/2158081/53442825-6c25a080-3a0a-11e9-84ea-7fa447e0d87a.png">

**Comment by russss** [comment]
The issue here is that for larger substations they're very obvious at that zoom level. So to improve this, the decision to switch from point to node has to be based on the size of the substation. 

It's not clear whether I can do this easily in Mapbox GL.

**Comment by flacombe** [comment]
Can't you preprocess the data to get the area in m2?
Then it'll be more easy to adapt depending on zoom level

**Comment by pyrog** [comment]
Fine, thank you 😊

[Zoom 15](https://openinframap.org/#15/46.5819/5.74361)
<img width="559" alt="Capture d’écran 2019-03-19 à 16 41 52" src="https://user-images.githubusercontent.com/2158081/54620089-f4c1ba80-4a65-11e9-9827-a71f4fc01a98.png">
