### ISSUE TITLE
Display circuits and cables in popup

### ISSUE THREAD

**Issue by pyrog** [openinframap/styles#49]
`cables` and `circuits` keys are not yet displayed in the popup:

key | value
-- | --
**cables** | 9
**circuits**|3
name|Flå - Nes
operator|Glitre Energi
power|line
voltage|132000;66000;66000

[way 683260414
![Screenshot_2019-06-06 Open Infrastructure Map(5)](https://user-images.githubusercontent.com/2158081/59062775-f18cdc80-88a6-11e9-88ef-90409f6be06a.png)
](https://openinframap.org/#17.9/60.60591/9.076344)

**Comment by Gazer75** [comment]
Add frequency for each voltage if noted like on https://www.openstreetmap.org/way/46832310

**Comment by flacombe** [comment]
I'd add that frequency should go in circuit relations and not on the physical line.

This requires a formal proposal to be voted on, but physically the frequency isn't a property of the line but about the electricity the line carries.
