### ISSUE TITLE
Render higher wattage plants over lower wattage plants at low zoom levels

### ISSUE THREAD

**Issue by rivermont** [openinframap/styles#52]
When two plants are close together, at low zoom levels (depends on distance between plants) only one is rendered, or only one name is rendered. Currently this seems to be random. It makes more sense to render the plant with the larger output (usually in MW), similar to how OSM Carto tries to render cities with larger populations over smaller ones (I think).

Example: The [Mountaineer Plant](https://osm.org/way/186792675) has an output capacity of 1300 MW, while the nearby [Philip Sporn Plant](https://osm.org/way/186792678) has an output capacity of 600 MW. However when zooming out, the smaller Philip Sporn Plant is shown.

![high zoom](https://user-images.githubusercontent.com/25139386/61156348-2a7d2a00-a4c1-11e9-91c1-1c9451ca436c.png)

![low zoom](https://user-images.githubusercontent.com/25139386/61156349-2b15c080-a4c1-11e9-9217-8650de68ade4.png)

**Comment by russss** [comment]
This should already be happening but it isn't for reasons I'm unclear on. Will need further investigation.

**Comment by russss** [comment]
Fixed this, finally.
