### ISSUE TITLE
Bad links to OSM nodes

### ISSUE THREAD

**Issue by flacombe** [openinframap/styles#55]
Hi

There is actually an issue with OSM nodes links in infoboxes I thought it was already knew.
When you click on such links, you get redirected to /way/ instead of /node/
https://openinframap.org/#16.95/45.739222/0.404235

Bad link : https://www.openstreetmap.org/way/1539545395
Good link : https://www.openstreetmap.org/node/1539545395

It may be good to replace way with node to solve the issue

All the best

**Comment by russss** [comment]
It is known, it's in openinframap/web#6

**Comment by flacombe** [comment]
Sure, sorry for noise, didn't look in the right project :(
