### ISSUE TITLE
Can't run Tegola server: SQL syntax error on power_line layer

### ISSUE THREAD

**Issue by flacombe** [openinframap/styles#58]
Hi

When trying to run Tegola server locally with OIM setup on my computer, I've got a SQL syntax error that prevent to retreive Geometry type of power_line (the first) layer.

Here is the command I run : ./tegola serve --config /data/osm/styles/config.toml
And the result I get : 
2019-10-27 22:22:32 [INFO] root.go:61: Loading config file: /data/osm/styles/config.toml
2019-10-27 22:22:32 [INFO] config.go:207: loading local config (/data/osm/styles/config.toml)
Error: could not register providers: error fetching geometry type for layer (power_line): ERREUR: erreur de syntaxe sur ou près de « ANY » (SQLSTATE 42601)

My db is properly configured with postgis, filled with imposm3, postgis-vt-utils has been setup.

Full SQL query is as this :
SELECT osm_id AS gid, ST_GeometryType(ST_Simplify(geometry, ZRes(ANY('{0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24}')) / 5, true)) AS geom, tunnel, location, first_semi(frequency) AS frequency, type, name, line, ref, char_length(ref) AS ref_len, convert_voltage(voltage) / 1000 AS voltage, convert_voltage(nth_semi(voltage, 2)) / 1000 AS voltage_2, convert_voltage(nth_semi(voltage, 3)) / 1000 AS voltage_3, operator FROM osm_power_lines WHERE geometry && ST_MakeEnvelope(-2.0663680475625e+07,-2.0663680475625e+07,2.0663680475624997e+07,2.0663680475624997e+07,3857) AND ST_Length(geometry) > ZRes(0) AND (line NOT IN ('bay', 'busbar') OR 0 > 10) ORDER BY convert_voltage(voltage) ASC NULLS FIRST LIMIT 1

I don't understand why there is ANY('{0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24}') while the config.toml states that power_line layer goes from Z2 to Z17.

Any hint regarding that plase?

All the best

**Comment by russss** [comment]
This is because I'm currently running a patched version of Tegola. 

This isn't necessary if we set the `geometry_type` key in the config.toml but I'm not in a position to test that change at the moment.

**Comment by flacombe** [comment]
Thanks

Indeed it worked when defining geometry_type in providers item section.

**Comment by russss** [comment]
I've added these geometry_type keys now.

**Comment by flacombe** [comment]
Thank you Russss
