### ISSUE TITLE
Increase visibilty of railway lines on base map

### ISSUE THREAD

**Issue by boothym** [openinframap/styles#61]
Hope this is the correct place to report this issue.

I noticed on the vector base map for OIM, railway lines do not appear until z13 - and even then they are not as easy to see compared to the much more prominent white roads. 

I was looking at the proximity of high voltage power lines to unelectrified railway lines, but it was difficult to work out where the railway lines are located at z10-12.

Or would it be possible to offer the default OSM standard layer (and/or Mapnik grayscale like OpenRailwayMap) as a base map choice?

**Comment by russss** [comment]
I've made these a bit more visible now.

**Comment by boothym** [comment]
Excellent, thanks! 👍
