### ISSUE TITLE
Import plant:storage

### ISSUE THREAD

**Issue by russss** [openinframap/styles#63]
We should show the storage capacity for storage plants. (Maybe for generators too?)

**Comment by flacombe** [comment]
The sortage capability is certainly a generator matter
You often found in a single plant, generators able to pump and other that can't.

Mapping practice will put plant:method=water-pumped-storage on power=plant and adapt generator:method value on individual generators according to their capabilities.

**Comment by russss** [comment]
[plant:storage](https://wiki.openstreetmap.org/wiki/Key:plant:storage) is a key I have recently added to indicate how much energy can be stored by the whole plant (in a similar way to `plant:output`) - this is clearly a plant-level feature.

I'll also add generator:method to the next import.

**Comment by flacombe** [comment]
Storage isn't similar to output energy calculus. See the discussion I've started on wiki
