### ISSUE TITLE
Hydroelectric tunnels

### ISSUE THREAD

**Issue by jidanni** [openinframap/styles#69]
OK you got this big intake, https://openinframap.org/?#17.9/24.179036/120.842279
but not the water tunnel leading in to it https://www.openstreetmap.org/way/219360672 .
Hope it is tagged enough.

**Comment by flacombe** [comment]
Hi jidanni

Mentioned features lack a bit of tagging.
See this proposal and associated tags : https://wiki.openstreetmap.org/wiki/Proposed_features/Hydropower_water_supplies

Is what you call "intake" is the actual powerhouse?
generator:source is not compatible with power=plant, see plant:source instead

On this fork of openinframap, you'll get the full water course rendered : http://map.infos-reseaux.com/#14.55/45.21843/6.71981
Sources are here https://github.com/flacombe/oim-web/blob/master/src/style/style_oim_water.js

It would be great to have it worldwide indeed

**Comment by jidanni** [comment]
> Is what you call "intake" is the actual powerhouse?

(All I know is on the hill there is this big circular hole with a gate over it. And then a few hundred meters northwest are the buildings.)

**Comment by flacombe** [comment]
Isn't this a surge tank intended to mitigate water pressure in case of emergency stop ?
https://wiki.openstreetmap.org/wiki/Tag:pipeline%3Dsurge_tank

Is there any water at the bottom of this hole?

**Comment by jidanni** [comment]
I'm sure there is plenty of water at the bottom. OK I added some more tags to
https://www.openstreetmap.org/way/518266491 . Thanks.

**Comment by flacombe** [comment]
Hi

We'll trying to progress on this
According to undergoing discussion on pipeline=surge_tank, your polygon shouldn't get it.
See these examples : 
https://www.openstreetmap.org/node/2507564653
https://www.openstreetmap.org/node/2398809588
A  separate fence or building can surround the surge_tank node usually linking two section of tunnel or pipelines.

Furthermore, here are more hint regarding the used tagging.
* power=hydro isn't recommended. I think you meant power=plant + plant:source=hydro. However this surge tank isn't the plant properly. It's only a particular component ensuring security of downstream turbines and valves.
Hydropower plants are usually described as relations involving the whole facility : https://www.openstreetmap.org/relation/3107022
* You have to find the actual generators according to local knowledge or publicly available documents under the appropriate license.

Feel free to show me additional contribution to progress toward a more accurate description if you want to.

**Comment by jidanni** [comment]
OK, someone who is more familiar with the area commented,
https://www.openstreetmap.org/changeset/82034449
And I told him to please correct it to what it really is and he did,
https://www.openstreetmap.org/way/518266491/history
So um... this is all over my head now. Beyond my comprehension.
So I guess I'll close this bug.

**Comment by flacombe** [comment]
Tagging guidelines are still not applied on the case you mention to start this issue.
As I'm not knowledgable, I can't make appropriate corrections.

However, power=hydro + generator:* can't be a valid combination, no exceptions.

**Comment by jidanni** [comment]
Maybe you could communicate that to that editor. Thanks.
