### ISSUE TITLE
Bring back city names in positron

### ISSUE THREAD

**Issue by flacombe** [openinframap/styles#72]
Currently OpenInfraMap doesn't display city names on the map background.
It makes things harder for users to locate themselves in a place they don't know.

Is it possible to bring back city names, even a few ones, to allow a better location at first sight please?

**Comment by rivermont** [comment]
One option might be to use the [`population` key ](https://wiki.openstreetmap.org/wiki/Key:population) and only display cities over a certain size.  
This would limit any crowding that would block infrastructure.

**Comment by flacombe** [comment]
I've restored it completely here : http://map.infos-reseaux.com/#9.64/46.0885/6.1366
It's possibly not the best option, but many names don't bother me either.

**Comment by russss** [comment]
Done!

**Comment by flacombe** [comment]
This is sweet, thank you
