### ISSUE TITLE
Continuous update without osmosis

### ISSUE THREAD

**Issue by flacombe** [openinframap/styles#78]
Hi,

I remember a discussion in the late December 2019 about bugs in continuous update with osmosis. I can't find anymore where the issue was opened unfortunately.
Someone (maybe you @russss ) told me osmosis wasn't necessary to run this continuous update.

Is it possible to add update scripts to this repository as I don't see how imposm3 can catchup with osm diff statuses, please?

The current script I use is :
```
osmosis --rri workingDirectory=. --wxc update.osc.gz && \
/opt/imposm3/imposm3 diff -quiet -config /opt/oim-styles/osmosis/imposm3.conf update.osc.gz
```

with the traditional osmosis configuration:
```
# The URL of the directory containing change files.
baseUrl=https://planet.openstreetmap.org/replication/minute

# Defines the maximum time interval in seconds to download in a single invocation.
# Setting to 0 disables this feature.
maxInterval=0
```

This currently produces duplicates for a given updated geometry : I see both the previous and current versions on the tiles.

All the best

**Comment by russss** [comment]
I just use `imposm run` as [described here](https://imposm.org/docs/imposm3/latest/tutorial.html#run). This runs continuously to fetch updates - there's no need for any script to drive it.

If you're seeing duplicates, it may be because you didn't run the initial `imposm import` with the `-diff` option.

**Comment by flacombe** [comment]
This is indeed way better and way simpler.
Thank you, I've removed osmosis and my updating timer.

I don't see any duplicate or persistent deleted geometries, great.
