### ISSUE TITLE
pipeline=marker

### ISSUE THREAD

**Issue by lufticus** [openinframap/styles#80]
I see that you can select oil and gas infrastructure on the OIM, so that gas pipelines, for example, become visible. Is it possible to display the visible markers on the surface, which are mapped with pipeline=marker, on this layer? There you will also find tags with the references to the pipeline name and operator.

**Comment by russss** [comment]
This is a duplicate of #32 - I will get round to it eventually!

**Comment by flacombe** [comment]
@lufticus I agree on displaying marker positions on OIM.
Please note pipeline=marker is now discouraged and replaced by marker=* + utility=*

All the best
