### ISSUE TITLE
views.sql : Undefined column name in power_substation_relation

### ISSUE THREAD

**Issue by flacombe** [openinframap/styles#83]
According to views.sql, line 22, name columns should exist in power_substation_relation table :
```sql
SELECT osm_id, geometry, name, voltage, substation, tags, construction
                  FROM power_substation_relation;
```

In power.py mapping, this table isn't supposed to have a name column. is it correct?
```py
relation_tables(
    "power_substation_relation",
    {
        "power": ["substation", "sub_station"],
        "construction:power": ["substation", "sub_station"],
    },
    relation_types=["site"],
    relation_columns=[
        str_col("substation"),
        str_col("voltage"),
        str_col("frequency"),
        str_col("construction:power", "construction"),
        bool_col("tunnel"),
    ],
)
```

This currently breaks views.sql execution when reloading database

**Comment by russss** [comment]
Imposm prefixes all its table names with `osm_` - the `power_substation_relation` table is the materialised view defined in [views.sql](https://github.com/openinframap/styles/blob/master/views.sql#L1) and the name column is extracted from the tags column by that view, so I think you just need to update that.

**Comment by flacombe** [comment]
Indeed, I missed update to tags -> 'name' AS name despite of rebase.
Thank you for answer and sorry for noise.

All the best
