### ISSUE TITLE
No Cyrillic symbols present on map view

### ISSUE THREAD

**Issue by un-logic** [openinframap/styles#84]
A few days ago I've noticed that map renders objects in a strange way, turned out it was missing all Cyrillic characters. Looks like a font related issue.
![Screenshot](https://user-images.githubusercontent.com/9430664/88399803-7eab3180-cdd8-11ea-8e92-ce381a45823e.png)
[Example location](https://openinframap.org/#15.31/53.509031/49.304616)
Notice that popup has all characters in place.

**Comment by russss** [comment]
This is now fixed - I had to change the source of the fonts due to issues with the base map tiles, but I've now changed it back.
