### ISSUE TITLE
generator:output:electricity always shows MW

### ISSUE THREAD

**Issue by tobylorenz** [openinframap/styles#86]
I've just added most photovoltaic generators in my location:
https://openinframap.org/#16.77/50.589819/8.61324

I used generator:output:electricity as documented here https://wiki.openstreetmap.org/wiki/Key:generator:output.
So for a generator with 37,95 kW, I added generator:output:electricity="37,95 kW".

But in the openinframap, the unit "kW" is disregarded. Instead it always shows MW.
So my generator now shows "37.95 MW".

**Comment by russss** [comment]
Coincidentally, I have literally just fixed this bug but it will take a while for the cache to update.

**Comment by tobylorenz** [comment]
Cool, cannot await to see it tomorrow, when the cache is updated :-) Thank you!
