### ISSUE TITLE
Simple file moves

### ISSUE THREAD

**Issue by flacombe** [openinframap/styles#88]
Hi Russss,

Is it possible to move the following files:
* `refresh_matviews.sql` to schema/ directory
* `layers.yml`, `util/generate_tegola_config.py`, `util/expire.py` to a new tegola/ directory

please ?

As to ease the maintenance of my forked project

Maybe `config.toml` files should be added to `.gitignore` as well as to not commit them?

**Comment by russss** [comment]
I've done this now.

**Comment by flacombe** [comment]
Really nice, thank you
