### ISSUE TITLE
How to use expire.py

### ISSUE THREAD

**Issue by flacombe** [openinframap/styles#89]
I'm looking for guidelines to use `util/expire.py` script?

Should it be put in a crontab or something?

It seems to use imposm-expire. Is it always enabled or should I modify my mapping configuration?

**Comment by russss** [comment]
I'm running imposm3 with `-expiretiles-dir /home/osm/imposm-expire` ([documentation here](https://imposm.org/docs/imposm3/latest/tutorial.html#expire-tiles) - for some reason it doesn't seem like you can set that option in config.json). 

The expire.py script is run on a timer every 1 minute.

I've made some updates to expire.py to tidy it up a bit.
