### ISSUE TITLE
Increase zoom level before displaying minor lines?

### ISSUE THREAD

**Issue by Gazer75** [openinframap/styles#9]
I think map would look less cluttered if you moved minor lines to z10 or 11.
At z9 its just a big blob.

**Comment by russss** [comment]
I'm not actually taking minor_line into consideration here, I do it all by voltage. I'm going to bump the minimum zoom level for low/undefined voltages down by one click and we'll see how that improves things. (I don't have any way of clearing the cache at the moment so it'll take a few days to take effect.)

**Comment by gustavecha** [comment]
Hi Russss

There is a whole pull request to review regarding this
We also miss transformers, switches, portals...
