### ISSUE TITLE
Remove postgresql credentials from config files

### ISSUE THREAD

**Issue by flacombe** [openinframap/styles#91]
Some postgresql credentials are found in files 
* `tegola/tegola.yml`
* probably in imposm3.conf file (not on this repository)

A ~/.pgpass file should be used for pgsql password authentication and credentials removed from config files
https://www.postgresql.org/docs/9.3/libpq-pgpass.html

**Comment by russss** [comment]
I'm not especially concerned about this as I'm not using the database credentials for security. At any rate there's no sensitive data in there.
